### PR TITLE
Group Work into Master

### PR DESCRIPTION
**Pull request by qwergram**
Project Guide: http://faculty.edcc.edu//paul.bladek/CS133/p4.htm
Latest Tests: https://travis-ci.org/qwergram/CS133Assignment

### CODE REVIEW

**Review by qwergram — COMMENTED** [review]
About: #12

**Review by qwergram — COMMENTED** [review]
About: #12

**Review by qwergram — COMMENTED** [review]
resolve #17

**Review by ctongGH — APPROVED** [review]

**Review by ctongGH — APPROVED** [review]

**Review by ctongGH — APPROVED** [review]

**Review by ctongGH — APPROVED** [review]

**Review by ctongGH — APPROVED** [review]

**Review by ctongGH — APPROVED** [review]

**Review by ctongGH — APPROVED** [review]

**Comment by qwergram** [comment]
[Turn in document](https://github.com/qwergram/CS133Assignment/blob/Tabitha/Notes/project4.md)
This is what we'll turn into Mr. Bladek. Do not turn it in until I merge this branch to master.

**Review by ctongGH — APPROVED** [review]

**Review by ctongGH — APPROVED** [review]

**Review by TabithaRoemish — APPROVED** [review]

**Comment by qwergram** [comment]
Good work team!

**Pull request merged**
